name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/pewpewzorp/buildozer:main
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK
        run: |
          export FORCE_ROOT=1
          buildozer android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
